In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
df = pd.read_csv('eng_dataset.csv',sep=',')

In [9]:
df.head()

ID sentiment                                            content
0  10941     anger  At the point today where if someone says somet...
1  10942     anger  @CorningFootball  IT'S GAME DAY!!!!      T MIN...
2  10943     anger  This game has pissed me off more than any othe...
3  10944     anger  @spamvicious I've just found out it's Candice ...
4  10945     anger  @moocowward @mrsajhargreaves @Melly77 @GaryBar...

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7102 entries, 0 to 7101
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ID         7102 non-null   int64 
 1   sentiment  7102 non-null   object
 2   content    7102 non-null   object
dtypes: int64(1), object(2)
memory usage: 166.6+ KB


In [11]:
df['sentiment'].unique()

array(['anger', 'fear', 'joy', 'sadness'], dtype=object)

In [12]:
len(df['ID'])

7102

In [13]:
anger = df[df['sentiment']=='anger']

In [14]:
len(anger)

1701

In [15]:
df['sentiment'].value_counts()

fear       2252
anger      1701
joy        1616
sadness    1533
Name: sentiment, dtype: int64

In [16]:
df.isnull().sum()

ID           0
sentiment    0
content      0
dtype: int64

In [17]:
X = df['content']
y = df['sentiment']

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

print('Training dta shape for X: ', X_train.shape)
print('Training dta shape for y: ', y_test.shape)

Training dta shape for X:  (5681,)
Training dta shape for y:  (1421,)


In [20]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

In [21]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),
                     ('clf',LinearSVC())])

In [22]:
#Feed the training data to the pipeline
text_clf.fit(X = X_train,y = y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [23]:
predictions = text_clf.predict(X_test)

In [24]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[330  21   3  21]
 [  9 406   4  15]
 [  1   9 305   4]
 [ 18  25  11 239]]


In [25]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

       anger       0.92      0.88      0.90       375
        fear       0.88      0.94      0.91       434
         joy       0.94      0.96      0.95       319
     sadness       0.86      0.82      0.84       293

    accuracy                           0.90      1421
   macro avg       0.90      0.90      0.90      1421
weighted avg       0.90      0.90      0.90      1421



In [26]:
print(metrics.accuracy_score(y_test,predictions))

0.9007741027445461


In [27]:
myphrases = ['smile']
prediction = text_clf.predict(myphrases)
print(prediction)

['joy']


In [ ]:
utral. Sentiment analysis is often performed on textual data to help businesses monitor brand and product sentiment in customer feedback, and understand customer needs.